# ai模块
ai:
  # 作者
  author: yxx

# 日志级别
logging:
  level:
    org.springframework.ai: debug

spring:
  ai:
#    data:
#      redis:
#        host: localhost
    # Ollama 模型
    ollama:
      base-url: http://localhost:11434
      chat:
#        model: deepseek-r1:7b
        model: deepseek-r1:1.5b
    # API 调用模型
    openai:
      # OpenAI/Aliyun配置模型：
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-352f74d9c61643db8a1ac870059a9020
      # 会话模型
      chat:
        options:
          # qwen3-max
          model: qwen-max-latest
          temperature: 0.8
      # 向量模型
      embedding:
        options:
          model: text-embedding-v3
          # 维度
          dimensions: 1024

    mcp:
      client:
        stdio:
          # 指定MCP服务器配置文件
#          servers-configuration: classpath:drawio-mcp-server.json
